### ISSUE TITLE
Road to ICE

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/hydration-node#886]
### Todo:

- [ ] router in rust
- [ ] Benchmarks
- [ ] DCA intent testing
- [ ] DCA migration
- [ ] Solution Priority
- [ ] Solver performance
- [ ] Solver in node

### DCA intents
- matching DCA intent but dont need to be in the same block - so how to align them so they match ?!
- DCA trigger if there is a trade in opposing direction. 

### FRONTEND
- rework needed
- opportunity to fix issues with eg TWAP
